FROM registry.redhat.io/rhel9/rhel-bootc:latest

RUN dnf -y groupinstall "Server with GUI" "Virtualization Host" && \
    dnf -y install virt-install \
                   virt-viewer \
                   libvirt-client \
                   libvirt \
                   qemu-img \
                   qemu-kvm \
                   dconf \
                   gnome-shell-extension-desktop-icons && \
    dnf clean all

RUN systemctl enable virtqemud.socket libvirtd
RUN systemctl set-default graphical.target


# ------ Embed a Windows VM ------
COPY windows_server_2012_r2.qcow2 /var/lib/libvirt/images/windows_server_2012_r2.qcow2
RUN chown qemu:qemu /var/lib/libvirt/images/windows_server_2012_r2.qcow2 && \
    chmod 644 /var/lib/libvirt/images/windows_server_2012_r2.qcow2
    
COPY setup-windows-vm.sh /usr/local/bin/setup-windows-vm.sh
RUN chmod +x /usr/local/bin/setup-windows-vm.sh
COPY setup-windows-vm.service /etc/systemd/system/setup-windows-vm.service

RUN systemctl enable setup-windows-vm.service

RUN mkdir -p /root/Desktop
COPY files/Windoes-VM.sh /root/Desktop/Windoes-VM.sh

# ------ Some Settings ------
# Create dconf profile for GDM if it doesn't exist
RUN mkdir -p /etc/dconf/profile /etc/dconf/db/gdm.d
RUN echo -e "user-db:user\nsystem-db:gdm\nfile-db:/usr/share/gdm/greeter-dconf-defaults" > /etc/dconf/profile/gdm

# Enable On-Screen Keyboard for Login Screen (GDM)
RUN echo -e "[org/gnome/desktop/a11y/applications]\nscreen-keyboard-enabled=true" > /etc/dconf/db/gdm.d/01-screen-keyboard

# Enable On-Screen Keyboard and desktop icons for User Session (Default for new users)
RUN mkdir -p /etc/dconf/db/local.d
RUN echo -e "[org/gnome/desktop/a11y/applications]\nscreen-keyboard-enabled=true" > /etc/dconf/db/local.d/01-screen-keyboard
RUN echo -e "[org/gnome/shell]\nenabled-extensions=['desktop-icons@gnome-shell-extensions.gcampax.github.com']" >> /etc/dconf/db/local.d/01-extensions
RUN dconf update


# ------ Perform checks on the final image. should always be the last line. ------
RUN bootc container lint
